### ISSUE TITLE
It should be allowed to Rename Category / Product / Topic / Criteria without breaking the projects that are pointing to it

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#104]
Currently, the name is part of the ID. This should be fixed so it's possible to rename w/o breaking the projects that are pointing to it.

**Comment by Pavek** [comment]
Name is part of ID for updateOrInsert mecahnism which requires something unique to look for (otherwise the same item will be added on every server restart) and we use name because of the lack of anything else. So, the possible solution are:

1. Add IDs to JSON file
Cons: need to manually ensure uniqueness, error-prone

2. Update name in both JSON & DB. Steps are:
- commit new name & push to dev/master
- before pushng to Heroku, go to production DB and change name to match new name
- push to Heroku > will restart server and update of public collections' fields
Cons: error-prone

3. Drop public collection(s) before push to Heroku.
Public collections will be create anew on next server restart.

4. The correct way: edit public collections with a custom provate CRUD app
Cons: time

Note: in any case changing name will lead to a duplicate in a selection list if the item is already selected by user (copy of item with old name is made).

Please elaborate or let's discuss.
