### ISSUE TITLE
Need to log out a user after session is expired

### ISSUE THREAD

**Issue by Pavek** [PeerSay/Atlas#109]
This is partially done on server already: user will be redirected to login page if the session is expired and normal naviration happens (e.g. F5).

But 'normal navigation' rarely happens in single-page-app, so we need to handle this case too.

**Comment by assafharel** [comment]
I have 2 problems with the recent deployment to Heroku
1. I fail to login with LinkedIn
I signed out as Admin@peer-say.com and try to login with LinkedIn - I get the projects page, and then immediately back to login. Seems like your fix to 109 (that signs me out for some reason).
I tried signing out of LinkedIn, but the problem is persistent (i.e. after I grant permission to my LinkedIn, I get bumped out).
2. Patch failure on project 5pKzckNm. I got in as Admin@peer-say.com,

**Comment by Pavek** [comment]
1. fixed with a968eb
2. fixed with 6f20afe (unrelated to this issue)
