### ISSUE TITLE
Add a "Done" button at the end of every page (except the dashboard). The button leads to the Dashboard

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#130]

**Comment by assafharel** [comment]
Please put a "Done" button a the bottom right corner of Criteria, Products and Essentials.
We had a usability session yesterday with users in Check Point, and they were annoyed that they didn't know what to do, when done writing essentials, or selecting criteria.

Thanks,
Assaf

**Comment by Pavek** [comment]
Let me argue this:
- Done button at the bottom is hardly ever visible until we need to invent
some complex (and potentially buggy) float layout for it.
- it was supposed to be fixed by #128 - Saving.../Saved (which will be in
Navbar, that is always visible). Google docs work this way and we need to
communicate this to users I think.
- the problem of 'not knowing what's next' is indeed possible. Arguably
better solution may be nicely thought/designed 'Introduction guide' similar
to what G+/Facebook etc. have.



Pavel

**Comment by assafharel** [comment]
I agree regarding “Saving…”. still, you had to see the look on the face of the user when he finished editing and didn’t know what to do next.
“Done”, or maybe “Dashboard” link, that would take the user to the Dashboard, would have solved that feeling (and then you have to understand the dashboard, which is a different issue…).

Another possible suggestion, is to add links at the bottom of every page to take the users to Criteria, Products and Decision Table.
The idea is to not leave the user hanging at the end of the page, as this hang is not nice (makes you want to close the app).

Unlike you, I don’t like the overlay slide with explanations.
The message I’m getting from such explanations is that the app creators didn’t solve the usability, so here’s something that you have to read for several minutes to get yourself acquainted with a complicated UI.
We want the UI to be as intuitive and trivial as possible so it will easily learnable by simple browsing through it.

Regards,
Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732

**Comment by Pavek** [comment]
OK, so what is the decision, then? Still Back button at the bottom or links
(which are always accessible from sidebar, btw)?

Pavel

**Comment by assafharel** [comment]
Hi prefer "Done" button at the bottom right corner.
בתאריך Mon, Jul 13, 2015 ב-18:50 מאת Pavel Zhytko <notifications@github.com
