### ISSUE TITLE
Decision tables spinners are not shown in i.e. 

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#133]
We're talking about the up/down arrows  for weights and grades in the decision table.

**Comment by Pavek** [comment]
Cannot fix. IE just doesn't have this spinner buttons.
The control is a now standard, <input type="number" > and per spec browser
vendors are free to implement this control 'as they feel is better for
their platform/users'. This is usually a bad idea to change such default
behavior because
 vendors are likely to know better their users/platform and experience they
want.



Pavel

**Comment by assafharel** [comment]
OK, I understand.
Is there some other common practice to overcome this that is used by other applications? (maybe by using a different control?)

Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732

**Comment by Pavek** [comment]
First, support is quite good: http://caniuse.com/#feat=input-number (note:
mobile browsers doesn't have spinners by design, instead they open keyboard
with numbers - clever & simple).

Options are:
- Some people prefer 'back to 00x' approach and unify experience by
removing spinner controls:
http://stackoverflow.com/questions/3975769/disable-webkits-spin-buttons-on-input-type-number

- There is also polyfill but it doesn't work on IE11:
https://github.com/jonstipe/number-polyfill/issues/21

- There are libs that implement control from scratch and consistently:
https://jqueryui.com/spinner/ (But I think it is not wise to bring the
whole new & large lib just for one control).

- I  think this is OK to live with it, because if users are upset by lack
of spinners, the should file a bug with browser vendor and let them fix
that or switch browser if refused, if users are fine - then nothing to
worry.

--


Pavel

**Comment by assafharel** [comment]
Agreed. Closing this issue.
