### ISSUE TITLE
[Staging] The labels and instructions when creating a new project are unclear

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#155]
When creating a new project, the dialog that opens is now asking me to choose a category.
The label above the edit box says: 'Selected:'.
This is completely unclear.
The edit box itself says: 'Select or search a category or domain...'
(guessing this is the text - like in the 'Products' page).
But there is not enough space for the text so it is only partially shown and becomes unclear.

Suggestion:
The fixed label should say 'Select a category:'.
The drop-down's edit box should not say anything and remain empty.

**Comment by Pavek** [comment]
Essentially, this problem (and #154 too) is due to the fact that new control requires more space for 2 reasons:
 - lable text is long
 - items in drop-down list are long too

So, I propose to solve them by a) shorten the label and b) reserve more space for project tiles. This will look as following and I checked it solves the issue for *all resolutions*:
https://gyazo.com/0fa47ca21bb57ef4f1408b496624ef30
https://gyazo.com/869dd16ed6b9e5c3d825124763d5e027
https://gyazo.com/0a8339294e841591dc4a67128d0a6dfc
https://gyazo.com/0a86f889a085320b1e44b4a1d9684ff9
https://gyazo.com/399112aea860218ef91009438821de91

Note: 'Selected' was just a debug output and is removed now.
Note2: I'm about to implement this solution now as it's the simplest and can be reopened/imporved later.

**Comment by talbendavid** [comment]
I think the solution is good, at least for a while (might be an issue when
there are many projects - we have time for that).
We should take advantage of the extra space on the project tile to show
interesting info...



*Tal Ben-David*, *CEO & Co-**Founder*
+972.52.4739064
