### ISSUE TITLE
Tables in project view are out of alignment

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#29]
The current concept of the project view is that criteria are displayed once, but apply for the other tables.
The product and shortlist table become out of context.

**Comment by Pavek** [comment]
Not sure what it means - need to discuss.

**Comment by Pavek** [comment]
Cells with New Line issue.

**Comment by Pavek** [comment]
The issues is not only in rows that are higher than others due to '\n' chars in them. There's one more issue -- Grouping. Groups has collapse/uncollapse which is independent by current design. So, the proper 'Table rows alignment' would require sync of groups state -- mechanism that not exist today, including fixes to 3rd-party ngTable lib.

So far, a work-around is implemented (hover effect). I propose to postpone.
