### ISSUE TITLE
New landing page | Instead of grer rectangle draw a line under the font

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#56]
Hi Pavel,

According to Liad the grey background doesn't work with the PeerSay logo in the center of the navigation bar. Please change it just to an underline text.

Thanks,
Assaf
![screen shot 2015-04-06 at 11 18 09 am](https://cloud.githubusercontent.com/assets/8779321/7002161/e16b8d00-dc4e-11e4-97d0-f668121d52c3.png)

**Comment by Pavek** [comment]
Such issues are usually avoided in PSD: designers show all possible states of the menu/controls on the single page, so that everyone agrees upon them. Unfortunately, this is missing.

Also, I don't find textual descriptions of such issues adequate. They tend to become unnecessary longer threads: e.g. make underline bolder/brighter/anymated etc..

So, picture is always batter.
