### ISSUE TITLE
Adding New Product - labels should be aligned left

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#81]
The labels 'Name' and 'Description' should be aligned left to the same starting point.

**Comment by assafharel** [comment]
Ah? Your description is not clear enough. Please provide a print screen of the problem, and suggested solution. On my browser everything seems to be aligned perfectly.

**Comment by Pavek** [comment]
I think I understand this: it is about alignment of lables on Add New product form. So, here's how it will look after fix:
http://gyazo.com/d66fba3ca6fd0ef42d398c0a74bb47de

Notice the space ot the right of the labels, which is inevitable because it occupies the percents of the screen. For example, on narrower screen it looks fine too:
http://gyazo.com/30b4263eee88d141f67e772abb43e51e

Please confirm.

**Comment by talbendavid** [comment]
The alignment fix is correct.

Do you have to give the labels percentage?
Can't the labels have fixed size and just the edit control be adjustable?
In any case - it is not critical.

Tal



*Tal Ben-David*, *CEO & Co-**Founder*
+972.52.4739064

**Comment by assafharel** [comment]
Notice that the same should be done to criteria as well...

**Comment by Pavek** [comment]
>Do you have to give the labels percentage?
>Can't the labels have fixed size and just the edit control be adjustable?

Answer:
This is how Horizonatal Forms are implementd in Boostrap:
http://getbootstrap.com/css/#forms-horizontal
Note also that fixed size is bad idea - consider you want to change lable to longer one or, more importantly, translate.
